inicio/urls.py
from django.urls import path
from inicio import views 
from django.conf.urls.static import static
from django.conf import settings

app_name = 'inicio'

urlpatterns = [
    path('info_pagina/', views.info_pagina, name='info_pagina'),
    path('', views.inicio, name='inicio'),
    path('estudiantes/crear/', views.crear_estudiante, name='crear_estudiante'),
    path('estudiantes/', views.listado_estudiantes, name='estudiantes'),
    path('estudiantes/<int:pk>/', views.DetalleEstudiantes.as_view(), name='detalle_estudiantes'),
    path('estudiantes/<int:pk>/modificar/', views.ModificarEstudiantes.as_view(), name='modificar_estudiantes'),
    path('estudiantes/<int:pk>/eliminar/', views.EliminarEstudiantes.as_view(), name='eliminar_estudiantes'),
    # path('ckeditor/', include('ckeditor_uploader.urls')),   
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

repaso/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('inicio.urls')),
    path('usuario/', include('usuario.urls')),
    path('admin/', admin.site.urls),
    
    
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inicio/models.py
from django.db import models
from ckeditor.fields import RichTextField

class Estudiantes(models.Model):
        nombre = models.CharField(max_length=20)
        apellido = models.CharField(max_length=20, null=True)
        edad = models.IntegerField()
        fecha_nacimiento = models.DateField(null=True)
        descripcion = RichTextField(null=True)
        imagen = models.ImageField(upload_to='estudiantes_images/', null=True, blank=True) 

        def __str__(self):
                return f'Nombre: {self.nombre} - Edad:  {self.edad}'

inicio/forms.py
from django import forms
from .models import Estudiantes

# class CrearEstudianteFormulario(forms.Form):
#     nombre = forms.CharField(max_length=20)
#     apellido = forms.CharField(max_length=20)
#     edad = forms.IntegerField()
#     fecha_nacimiento = forms.DateField(required=False)
#     descripcion = forms.CharField(max_length=4000)
#     imagen = forms.ImageField(required=False)

class CrearEstudianteFormulario(forms.ModelForm):
    class Meta:
        model = Estudiantes
        fields = ['nombre', 'apellido', 'edad', 'fecha_nacimiento', 'descripcion', 'imagen']
        widgets = {
            'fecha_nacimiento': forms.DateInput(attrs={'type': 'date'})
        }
 
class BuscarEstudianteFormulario(forms.Form):
    nombre = forms.CharField(max_length=100)

inicio/views.py
from django.shortcuts import render, redirect
from django.shortcuts import render, get_object_or_404
from inicio.forms import CrearEstudianteFormulario, BuscarEstudianteFormulario
from inicio.models import Estudiantes
from django.http import HttpResponse 

from django.views.generic.edit import UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin



def inicio(request):
    return render(request, 'inicio/inicio.html')

def info_pagina(request):
    return render(request, 'inicio/info_pagina.html')

@login_required
def crear_estudiante(request):
    mensaje = ''

    if request.method == 'POST':
        formulario = CrearEstudianteFormulario(request.POST, request.FILES)
        if formulario.is_valid():
            info = formulario.cleaned_data
            estudiante = Estudiantes(nombre=info['nombre'], apellido=info['apellido'], edad=info['edad'], fecha_nacimiento=info['fecha_nacimiento'], descripcion = info['descripcion'], imagen=info['imagen'])
            estudiante.save()
            mensaje = f'Se creo el estudiante {estudiante.nombre}'
                                    
        else:
            return render(request, 'inicio/crear_estudiante.html', {'formulario': formulario})

    formulario = CrearEstudianteFormulario()
    return render(request, 'inicio/crear_estudiante.html', {'formulario': formulario, 'mensaje': mensaje})


@login_required
def listado_estudiantes(request):

    formulario = BuscarEstudianteFormulario(request.GET)
    listado_estudiantes = Estudiantes.objects.all()
    if formulario.is_valid():
        nombre_a_buscar = formulario.cleaned_data.get('nombre', '')
        listado_estudiantes = Estudiantes.objects.filter(nombre__icontains=nombre_a_buscar)

    

    formulario = BuscarEstudianteFormulario()
    return render(request, 'inicio/estudiantes.html', {'formulario': formulario, 'listado_estudiantes': listado_estudiantes})
 
class DetalleEstudiantes(DetailView):
     model = Estudiantes
     template_name = "inicio/detalle_estudiantes.html"


@login_required
def modificar_estudiantes(request, estudiante_id):
    estudiante = get_object_or_404(Estudiantes, pk=estudiante_id)

    if request.method == 'POST':
        form = CrearEstudianteFormulario(request.POST, request.FILES, instance=estudiante)
        if form.is_valid():
            form.save()
            return redirect('inicio:estudiantes')

    else:
        form = CrearEstudianteFormulario(instance=estudiante)

    return render(request, 'inicio/modificar_estudiantes.html', {'form': form, 'estudiantes': estudiante})


# class ModificarEstudiantes(UpdateView):
#      model = Estudiantes
#      fields = ['nombre', 'apellido', 'edad', 'fecha_nacimiento', 'descripcion']
#      template_name = "inicio/modificar_estudiantes.html"
#      success_url = reverse_lazy('inicio:estudiantes')

class ModificarEstudiantes(UpdateView):
    model = Estudiantes
    form_class = CrearEstudianteFormulario
    template_name = "inicio/modificar_estudiantes.html"
    success_url = reverse_lazy('inicio:estudiantes')
     

class EliminarEstudiantes(DeleteView):
    model = Estudiantes
    template_name = "inicio/eliminar_estudiantes.html"
    success_url = reverse_lazy('inicio:estudiantes')

inicio/templates/inicio/crear_estudiante.html
{% extends 'base.html' %}

{% block title_head %}
<title>Crear estudiante</title>
{% endblock title_head %}

{% block h1_header %}
Crear estudiante
{% endblock h1_header %}

{% block contenido %}

{% if mensaje %}
  <div class="alert alert-success">
    {{ mensaje }}
  </div>
{% endif %}

{% comment %} <form action= {% url 'inicio:crear_estudiante' %} method="post"> {% endcomment %}
<form action="{% url 'inicio:crear_estudiante' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
    <table>
            {{formulario}}
            {{formulario.media}}
    </table>
    <button>Crear</button>
</form>

{% endblock contenido %}

inicio/templates/inicio/detalle_estudiantes.html
{% extends 'base.html' %}

{% block title_head %}
<title>Estudiantes</title>
{% endblock title_head %}

{% block h1_header %}
Datos del estudiantes {{estudiantes.nombre}}
{% endblock h1_header %}

{% block contenido %}
<li>Nombre: {{estudiantes.nombre}}</li>
<li>Apellido: {{estudiantes.apellido}}</li>
<li>Edad: {{estudiantes.edad}}</li>
<li>Fecha de nacimiento: {{estudiantes.fecha_nacimiento}}</li>
<li>Descripcion: {{estudiantes.descripcion | safe}}</li>
{% if estudiantes.imagen %}
    <li><img src="{{ estudiantes.imagen.url }}" alt="{{ estudiantes.nombre }}"></li>
{% else %}
    <li>No hay imagen disponible.</li>
{% endif %}
{% comment %} <li><img src="{{ estudiantes.imagen.url }}" alt="{{ estudiantes.nombre }}"></li> {% endcomment %}
{% endblock contenido %}

inicio/templates/inicio/eliminar_estudiantes.html
{% extends 'base.html' %}

{% block title_head %}
<title>Eliminar estudiante</title>
{% endblock title_head %}

{% block h1_header %}
Eliminar estudiante {{estudiantes.nombre}}
{% endblock h1_header %}

{% block contenido %}


<form action= {% url 'inicio:eliminar_estudiantes' estudiantes.id %} method="post">
    {% csrf_token %}
    <p>Va a eliminar a {{estudiantes}}</p>
    <button>Confirmar</button>
</form>

{% endblock contenido %}

inicio/templates/inicio/estudiantes.html
{% extends 'base.html' %}

{% block title_head %}
<title>Estudiantes</title>
{% endblock title_head %}

{% block h1_header %}
Estudiantes
{% endblock h1_header %}

{% block contenido %}

<nav class="navbar navbar-light bg-light static-top">
    <div class="container">
        
        <button>
            <a class="navbar-brand" href={% url 'inicio:crear_estudiante' %}>Crear estudiante</a>
        </button>

        <form action={% url 'inicio:estudiantes' %}>
            <table>
                    {{formulario}}
            </table>
            <button>Buscar</button>
        </form>
    </div>
</nav>
        {% if listado_estudiantes %}
        {% for estudiantes in listado_estudiantes %}
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
        
                <li>
            {% comment %} <nav class="navbar navbar-light bg-light static-top">
                <div class="container"> {% endcomment %}

                    <a href={% url 'inicio:detalle_estudiantes' estudiantes.id %}>{{estudiantes}}</a>
                    <button>
                        <a class="navbar-brand" href={% url 'inicio:modificar_estudiantes' estudiantes.id %}>Modificar</a>
                    </button>
                    <button>
                        <a  class="navbar-brand" href={% url 'inicio:eliminar_estudiantes' estudiantes.id %}>Eliminar</a>
                    </button>
                {% comment %} </div>
            </nav> {% endcomment %}
                </li>
            </div>
        </nav>

{% endfor %}
{% else %}
<p>No hay datos</p>
{% endif %}

{% endblock contenido %}

inicio/templates/inicio/info_pagina.html
{% extends 'base.html' %}

{% block title_head %}
<title>Info Pagina</title>
{% endblock title_head %}

{% block h1_header %}
Proyecto final
{% endblock h1_header %}

{% block contenido %}
<p>
    La siguiente pagina fue realizada por Mariano
</p>
{% endblock contenido %}

inicio/templates/inicio/inicio.html
{% extends 'base.html' %}

{% block title_head %}
<title>inicio</title>
{% endblock title_head %}

{% block h1_header %}
Bienvenidos a mi pagina
{% endblock h1_header %}

{% block contenido %}
<p>
    Registro de estudiantes
</p>
{% endblock contenido %}

inicio/templates/inicio/modificar_estudiantes.html
{% extends 'base.html' %}

{% block title_head %}
<title>Modificar estudiante</title>
{% endblock title_head %}

{% block h1_header %}
Modificar estudiante {{estudiantes.nombre}}
{% endblock h1_header %}

{% block contenido %}


<form action="{% url 'inicio:modificar_estudiantes' estudiantes.id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        {{form.media}}
    </table>
    <button>Modificar</button>
</form>

{% if estudiantes.imagen %}
    <p>Imagen actual:</p>
    <img src="{{ estudiantes.imagen.url }}" alt="{{ estudiantes.nombre }}" width="200">
{% else %}
    <p>No hay imagen disponible.</p>
{% endif %}


{% comment %} 
<form action= {% url 'inicio:modificar_estudiantes' estudiantes.id %} method="post">
    {% csrf_token %}
    <table>
            {{form}}
    </table>
    <button>Modificar</button>
</form> {% endcomment %}

{% endblock contenido %}