inicio/urls.py
from django.urls import path
from inicio import views 
from django.conf.urls.static import static
from django.conf import settings

app_name = 'inicio'

urlpatterns = [
    path('info_pagina/', views.info_pagina, name='info_pagina'),
    path('', views.inicio, name='inicio'),
    path('estudiantes/crear/', views.crear_estudiante, name='crear_estudiante'),
    path('estudiantes/', views.listado_estudiantes, name='estudiantes'),
    path('estudiantes/<int:pk>/', views.DetalleEstudiantes.as_view(), name='detalle_estudiantes'),
    path('estudiantes/<int:pk>/modificar/', views.ModificarEstudiantes.as_view(), name='modificar_estudiantes'),
    path('estudiantes/<int:pk>/eliminar/', views.EliminarEstudiantes.as_view(), name='eliminar_estudiantes'),
    # path('ckeditor/', include('ckeditor_uploader.urls')),   
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

repaso/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('inicio.urls')),
    path('usuario/', include('usuario.urls')),
    path('admin/', admin.site.urls),
    
    
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuario/urls.py
from django.urls import path
from usuario import views
from django.contrib.auth.views import LogoutView

app_name = 'usuario'

urlpatterns = [
    path('login/', views.login, name = 'login'),
    path('logout/', LogoutView.as_view(template_name='usuario/logout.html'), name = 'logout'),
    path('registro/', views.registrarse, name='registrarse'),
    path('perfil/editar/', views.edicion_perfil, name='editar_perfil'),
    path('perfil/editar/password', views.ModificarPass.as_view(), name='modificar_pass'),
    path('lista_usuarios/', views.lista_usuarios, name='lista_usuarios')
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% block title_head %}
        <title>Landing Page - Start Bootstrap Theme</title>
        {% endblock title_head %}
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static 'css/styles.css' %} rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                {% comment %} <a class="navbar-brand" href={% url 'inicio:info_pagina' %}>Info Pagina</a> {% endcomment %}
                <a class="navbar-brand" href={% url 'inicio:inicio' %}>Inicio</a>
                {% comment %} <a class="btn btn-primary" href={% url 'inicio:crear_estudiante' %}>Crear estudiante</a> {% endcomment %}
                {% comment %} <a class="navbar-brand" href={% url 'inicio:listado_estudiantes' %}>Listado estudiantes</a>
                {% comment %} <a class="navbar-brand" href={% url 'inicio:crear_estudiante' %}>Crear estudiante</a> {% endcomment %}
                <a class="navbar-brand" href={% url 'inicio:estudiantes' %}>Estudiantes</a>
                {% if request.user.is_authenticated %}
                {% if request.user.infoextra.avatar %}      
                <img src={{request.user.infoextra.avatar.url}} alt=""height='40p'>
                {% endif %}
                <a class="navbar-brand" href={% url 'usuario:lista_usuarios' %}>{{request.user.username}}</a>
                <a class="btn btn-primary" href={% url 'usuario:logout' %}>Logout</a>
                {% else %}
                <a class="btn btn-primary" href={% url 'usuario:login' %}>Login</a>
                <a class="btn btn-primary" href={% url 'usuario:registrarse' %}>Registrarse</a>
                {% endif %}
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                                     
                            <h1 class="mb-5">
                                {% block h1_header %}
                                {% endblock h1_header %}
                            </h1>
               
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% block contenido %}
        <p>Soy el template padre!</p>
        {% endblock contenido %}

        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a class="navbar-brand" href={% url 'inicio:info_pagina' %}>About</a></li>
                      
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">Pagina realizada por Mariano Melidoni</p>
                    </div>
                    {% comment %} <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div> {% endcomment %}
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src={% static 'js/scripts.js' %}></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>